const i18Obj = {
    en: {
      'English': 'English',
      'Russian': 'Русский',
      'Good evening': 'Good evening',
      'Good morning' : 'Good morning',
      'Good night': 'Good night',
      'Good afternoon': 'Good afternoon',
      'Settings': 'Settings',
      "To do" : "To do",
      "Hide Elements" : "Hide Elements",
      "time": "Time", 
      "date": "Date",
      "greeting" : "Greeting",
      "quotes" : "Quotes",
      "weather" : "Weather",
      "player": "Audio Player",
      "Background": "Change Background",
      "Github": "Github collection",
      "choosePic" : "Choose your Flickr and Unsplash tag: ",
      "chooseLng" : "Choose Language",
      "Enter a tag" : "Enter a tag",
      "Enter your name :)" : "Enter your name :)",
      "Enter city" : "Enter city",   
      "weather-dscr" : "The city name is either empty, or incorrect. Please try again ^_^",
      "task" : "New task",
      "any-tasks" : "Any tasks? :)",
      "delete-tasks" : "Delete All",
      "Wind speed:" : "Wind speed: ",
      "m/s" : "m/s", 
      "Humidity:": "Humidity",
      "Minsk": "Minsk",
  },
    ru: {
      'English': 'English',
      'Russian': 'Русский',
      'Good evening': 'Добрый вечер',
      'Good morning' : 'Доброе утро',
      'Good night': 'Доброй ночи',
      'Good afternoon': 'Добрый день',
      'Settings': 'Настройки',
      "To do": "Список дел",
      "Hide Elements" : "Спрятать элементы", 
      "time": "Время", 
      "date": "Дата",
      "greeting" : "Приветствие",
      "quotes" : "Цитата дня",
      "weather": "Погода", 
      "player" : "Аудиоплеер",
      "Background": "Изменить фон",
      "Github" : "Коллекция Github",
      "choosePic" : "Выберете Flickr и Unsplash тэг: ",
      "chooseLng": "Выбрать язык",
      "Enter a tag": "Введите тэг",
      "Enter your name :)" : "Введите Ваше имя :)",
      "Enter city" : "Введите город",   
      "weather-dscr" : "Введено либо пустое, либо неправильное значение. Попробуйте еще раз ^_^",
      "task" : "Новая задача",
      "any-tasks" : "Список дел",
      "delete-tasks" : "Удалить всё",
      "Wind speed:" : "Скорость ветра: ",
      "m/s" : "м/с", 
      "Humidity:": "Влажность",
      "Minsk": "Минск",
    }
  }
  export default i18Obj